### PR TITLE
Added a simple keep-alive event

### PR DESCRIPTION
**Pull request by chevtche**

### CODE REVIEW

**Comment by tribal-tec** [comment]
Name it EVENT_HEARTBEAT. keepalive would be the action one takes to get more heartbeats

**Comment by hernando** [comment]
I didn't want to be pedantic, but I was thinking the same.

**Comment by tribal-tec** [comment]
Just thinking: the existing EVENT_ECHO would be sufficient, but probably semantically not correct, right?

**Comment by chevtche** [comment]
Echo seems false... There is no echo...

**Comment by hernando** [comment]
Unless you send KEEP_ALIVE from the peer and the receiver answers EVENT_ECHO, but that requires two publishers and subscribers, which is not the simplest solution.

I prefer adding the HEARTBEAT message.

**Comment by chevtche** [comment]
Ok. Updated.

**Comment by chevtche** [comment]
Can this me merged?

**Comment by hernando** [comment]
+2, I can't merge

**Comment by hernando** [comment]
Wait a second, you have to fix the commit message.

**Comment by chevtche** [comment]
Ok. Thank you.

**Comment by chevtche** [comment]
Ok. It's fixed.

**Pull request merged**
